export const questions = [
    "What have you created that you are most proud of?",
    "What is your favorite hobby?",
    "What is your dream vacation destination?",
    "What is the best book you've read recently?",
    "If you could have any superpower, what would it be and why?",
    "What is your go-to karaoke song?",
    "If you could instantly become an expert in something, what would it be?",
    "What's the most adventurous thing you've ever done?",
    "If you had a time machine, which era would you visit and why?",
    "What is your favorite way to relax and unwind?",
    "If you could meet any historical figure, who would it be and why?",
    "What is the most interesting fact you've ever learned?",
    "If you could have dinner with any fictional character, who would it be and why?",
    "What is your favorite childhood memory?",
    "What is a skill you have always wanted to learn?",
    "If you were stranded on a desert island, what three items would you want to have with you?",
    "What is the most unusual food you've ever tried?",
    "If you could choose any career, money aside, what would you do?",
    "What is your favorite season and why?",
    "If you could live in any fictional world, which one would you choose and why?",
    "What is your biggest pet peeve?",
    "What is your favorite way to spend a lazy Sunday?",
    "If you could have a dinner party with any five people, dead or alive, who would you invite?",
    "What is one thing you've always wanted to do but haven't had the chance?",
    "If you could have any talent, what would you choose?",
    "What is the most beautiful place you've ever visited?",
    "If you could learn any language instantly, which one would you choose?",
    "What is your favorite type of music?",
    "If you could be an expert in any sport, which one would you choose?",
    "What is the best advice you've ever received?",
    "If you could have a conversation with your future self, what would you ask?",
    "What is your favorite quote and why?",
    "If you could have any animal as a pet, what would it be and why?",
    "What is one thing you wish more people knew about you?",
    "If you could go back in time and change one thing, what would it be?",
    "What is your favorite outdoor activity?",
    "If you could have a supernatural ability, what would you choose and how would you use it?",
    "What is your favorite board game or card game?",
    "If you could meet any celebrity, who would it be and why?",
    "What is your favorite type of cuisine?",
    "If you could be a character from any movie, who would you choose and why?",
    "What is the most memorable concert or live performance you've attended?",
    "If you could be an expert in any field of science, which one would you choose?",
    "What is your favorite way to give back to the community?",
    "If you could have any hobby or skill instantly, what would it be?",
    "What is your favorite childhood game?",
    "If you could travel to any country, where would you go and why?",
    "What is your favorite type of art or artistic medium?",
    "If you could have any dessert right now, what would you choose?",
    "What is the best gift you've ever received?",
    "If you could have a conversation with any fictional character, who would it be and why?",
    "What is the most interesting place you've ever been to?",
    "If you could be an expert in any instrument, which one would you choose?",
    "What is your favorite way to celebrate achievements?",
    "If you could solve any world problem, which one would it be?",
    "What is your favorite quote about life and why?",
    "If you could have a personal chef, what type of food would you want them to cook?",
    "What is the best movie you've seen recently?",
    "If you could have any view from your window, what would it be?",
    "What is your favorite type of exercise or physical activity?",
    "If you could have any fictional creature as a pet, what would it be and why?"
];
